FROM alpine/git as clone 
WORKDIR /app
RUN git clone https://github.com/dsrcgithubtest/cicdproject.git

FROM maven:3.5-jdk-8-alpine as build 
WORKDIR /app
COPY --from=0 /app/cicdproject /app
RUN mvn install

ADD /target/cicdProject.war dsrcdemopipeline.war
ENTRYPOINT ["java","-jar","dsrcdemopipeline.war","--httpPort=9999"]
